# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Martin Bestawros
tagline:             A Personal Homepage
url:                 http://idevmartin.com
paginate:            1
baseurl:             "http://idevmartin.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Martin Bestawros
  url:               https://idevmartin.com
  email:             amt271@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
